# Generated by Django 5.0.3 on 2024-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionLog',
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=100040),
        ),
    ]
