# Generated by Django 5.0.3 on 2024-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_transaction_transactionlog_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='nim',
            field=models.CharField(default='13520040', max_length=10),
            preserve_default=False,
        ),
    ]
