# Generated by Django 5.0.3 on 2024-03-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transactionlog_nim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='nim',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nim',
            new_name='uid',
        ),
    ]
