# Generated by Django 5.0.3 on 2024-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nim_transactionlog_uid_rename_nim_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('TOPUP', 'Topup'), ('DEDUCT', 'Deduct')], default='DEDUCT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=10),
            preserve_default=False,
        ),
    ]
