# Generated by Django 5.0.3 on 2024-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactionlog_transaction_type_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$juFUvlsqNdtl1pyHZNNuMF$RrXnwmfHFZ09GPCKYixi1K9cgTX1ahWzqISG+vaggSs=', max_length=255),
        ),
    ]
