# Generated by Django 5.0.3 on 2024-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transactionlog_options_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=140000),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$usc25YTqNp6heSC13Vw0gq$cO96OJyzk3nH52yx7mazYAgq5d5ouV7zBPSnQMmDKbk=', max_length=255),
        ),
    ]
